### ISSUE TITLE
unix-version build instructions unclear

### ISSUE THREAD

**Issue by dgasaway** [rwtodd/bascat#2]
The instructions say to run 'configure'.  What is that?  I have no such command, though I have autoconf and automake installed.  Running 'autoconf' results in an error.

**Comment by rwtodd** [comment]
You can get the released source package ([https://github.com/rwtodd/bascat/releases/download/v1.1/bascat-1.1.tar.gz](https://github.com/rwtodd/bascat/releases/download/v1.1/bascat-1.1.tar.gz))  which has configure in it already ... but with the development sources you'd run `autoreconf -iv`, which will generate configure and create a bunch of other autotools files.  That is a common practice with autotools dev trees.

**Comment by dgasaway** [comment]
Understood.  It might be worthwhile to note that the instructions are for building from a release tarball.  And (optionally) offer instructions for building from a clone.  Some people don't know the ins-and-outs of autoconf, obviously. :)
